### ISSUE TITLE
Simulate User (FID Impersonation)

### ISSUE THREAD

**Issue by FTCHD** [FTCHD/frametrain#35]
TLDR: Currently we give users the option to simulate Following, Follower, Recasted, Shared. We should have a field at the bottom of the menu to input a custom FID to simulate. 

This involves changes in the `FramePreview` and `/p` route.

<img width="281" alt="simulate" src="https://github.com/FTCHD/frametrain/assets/144691102/070d4bb9-c1e8-411e-8fd2-818085d5312b">

**Comment by waptik** [comment]
Where should the fid be saved(localstorage, db cookies etc)?

**Comment by FTCHD** [comment]
It should work the same as the other options in the Popover, using an `atom`, not saving data anywhere.

Ideally, it would already be pre-populated with the FID of the currently logged user.

**Comment by FTCHD** [comment]
Every time you open a new frame it would pre populate it with your `FID`, and you can change it by typing in the `Input` below the 4 toggles. If you go to another frame the same happens, we can add persistence to the `atoms` a bit later (& it's mostly just a flag).
